/***************************************************************************************************
 * FILE: en.js
 *
 * PURPOSE
 * English Translation Dictionary
 *
 * IMPORTANT
 * This file registers itself with the localization registry.
 ***************************************************************************************************/
registerLanguage("en", {
  common: {
    appName: "ShopMate",
    footer: "© Wisemen IT Solutions",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    edit: "Edit",
    delete: "Delete",
    remove: "Remove",
    create: "Create",
    update: "Update",
    yes: "Yes",
    no: "No",
    ok: "OK",
    or: "OR",
    continue: "Continue",
    done: "Done",
    next: "Next",
    previous: "Previous",
    search: "Search",
    loading: "Loading...",
    comingSoon: "Coming Soon",
    more: "More",
    profile: "Profile",
    emailAddress: "Email Address",
    expand: "Expand",
    collapse: "Collapse",
  },
  auth: {
    login: "Login",
    logout: "Logout",
    emailAddress: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    firstName: "First Name",
    lastName: "Last Name",
    createShoppingGroup: "Create Shopping Group",
    forgotPassword: "Forgot Password?",
    invitedText: "Been invited to join a shopping group?",
    invitedSubText:
      "Use the invitation email sent to your registered email address.",
    tagline: "Manage your shopping together",
  },
  category: {
    addItem: "Add Item",
    editItem: "Edit Item",
    deleteItem: "Delete Item",
    purchased: "Purchased",
    favourite: "Favourite",
  },
  profile: {
    title: "Profile",
    personalInformation: "Personal Information",
    accountInformation: "Account Information",
  },
  settings: {
    title: "Settings",
    profile: "My Profile",
    security: "Security",
    theme: "Theme",
    notifications: "Notifications",
    language: "Language",
    currency: "Currency",
    measurementUnits: "Measurement Units",
    exportData: "Export Data",
    importData: "Import Data",
    about: "About ShopMate",
  },
  notifications: {
    title: "Notifications",
    all: "All",
    unread: "Unread",
    shopping: "Shopping",
    budget: "Budget",
    group: "Group",
    general: "General",
  },
  budget: {
    title: "Budget",
    monthlyBudget: "Monthly Budget",
    categoryBudget: "Category Budget",
    spent: "Spent",
    remaining: "Remaining",
  },
  dialogs: {
    themeUpdatedTitle: "Theme Updated",
    themeUpdatedMessage: "Your preferred application theme has been saved.",
    languageUpdatedTitle: "Language Updated",
    languageUpdatedMessage: "Your preferred language has been saved.",
    notificationUpdatedTitle: "Notification Preferences",
    notificationUpdatedMessage:
      "Your notification preferences have been updated successfully.",
  },
  register: {
    title: "Register",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    groupName: "Group Name",
    biometric: "Protect ShopMate with Biometrics",
    createGroup: "Create Shopping Group",
    alreadyHaveAccount: "Already have an account? Login",
    accountExistsTitle: "Account Already Exists",
    accountExistsMessage: "An account with this email address already exists.",
    successTitle: "Welcome to ShopMate!",
    successMessage:
      "Your shopping group has been created successfully.\n\nYou can complete your personal profile later from Profile Management.",
  },
  forgotPassword: {
    title: "Forgot Password",
    description:
      "Enter your registered email address to receive a password reset link.",
    emailPlaceholder: "Email Address",
    sendButton: "Send Reset Link",
    resetTitle: "Password Reset",
    resetMessage:
      "If an account exists with this email address, a password reset link has been sent.",
    missingEmailTitle: "Missing Email",
    missingEmailMessage: "Please enter your registered email address.",
  },
  dashboard: {
    title: "ShopMate Dashboard",
    noGroupSelected: "No Group Selected",
    selectOrCreateGroup: "Select or create a group",
    noCategories: "No categories yet",
    budget: "Budget",
    spent: "Spent",
    left: "Left",
    notSet: "Not Set",
    pending: "Pending",
    purchased: "Purchased",
    selectGroup: "Select Group",
    createNewGroup: "Create New Group",
    createGroupTitle: "Create Shopping Group",
    groupName: "Group Name",
    groupNamePlaceholder: "Shopping Group Name",
    enterGroupName: "Enter Group Name",
    createGroupButton: "Create Group",
    groupNameRequiredTitle: "Group Name Required",
    groupNameRequiredMessage: "Please enter a shopping group name.",
    groupExistsTitle: "Group Already Exists",
    groupExistsMessage: "A shopping group with this name already exists.",
    groupCreated: "Shopping group created successfully.",
    groupNameMinLength: "Group name must contain at least 2 characters.",
    groupNameMaxLength: "Group name cannot exceed 40 characters.",
    groupNameInvalidCharacters:
      "Only letters, numbers, spaces, apostrophes and hyphens are allowed.",
    groupNameRequired: "Please enter a group name.",
    groupAlreadyExists: "A group with this name already exists.",
    selectGroupTitle: "No Group Selected",
    selectGroupMessage: "Please select a shopping group first.",
    groupActions: "Group Actions",
    renameGroup: "Rename Group",
    inviteMember: "Invite Member",
    deleteGroup: "Delete Group",
    invitingMemberTo: "Inviting Member To",
    enterEmailAddress: "Enter Email Address",
    sendInvitation: "Send Invitation",
    emailRequired: "Please enter an email address.",
    invalidEmail: "Please enter a valid email address.",
    memberAlreadyExists: "This user is already a member of the group.",
    pendingInvitationExists: "A pending invitation already exists.",
    currentUserUnavailable: "Unable to determine the current user.",
    invitationSent: "Invitation sent successfully.",
    groupRenamed: "Group renamed successfully.",
    deleteGroupConfirmationStart: "Are you sure you want to delete",
    deleteGroupConfirmationDetails:
      "All categories, shopping items, budgets and members in this group will also be permanently deleted.",
    deleteGroupConfirmationWarning: "This action cannot be undone.",
    groupDeleted: "Group deleted successfully.",
    groupManagement: "Group Management",
    notifications: "Notifications",
    settings: "Settings",
    export: "Export",
    import: "Import",
    createCategoryTitle: "Create Category",
    categoryNamePlaceholder: "Category Name",
    categoryCreated: "Category created successfully.",
    categoryNameRequiredTitle: "Category Name Required",
    categoryNameRequiredMessage: "Please enter a category name.",
    categoryExistsTitle: "Category Already Exists",
    categoryExistsMessage: "A category with this name already exists.",
    categoryAlreadyExists: "A category with this name already exists.",
    categoryActions: "Category Actions",
    renameCategory: "Rename Category",
    deleteCategory: "Delete Category",
    setCategoryBudget: "Set Category Budget",
    enterCategoryName: "Enter category name.",
    categoryRenamed: "Category renamed successfully.",
    deleteCategoryConfirmation: "Are you sure you want to delete",
    categoryDeleted: "Category deleted successfully.",
    monthlyBudget: "Monthly Budget",
    unlimited: "Unlimited",
    allocated: "Allocated",
    remaining: "Remaining",
    unlimitedBudget: "Unlimited Budget",
    used: "Used",
    allocation: "Allocation",
    budgetUsage: "Budget Usage",
    allocationStatus: "Allocation Status",
    categoryBudgetsExceedGroupBudget:
      "Category budgets exceed the Group Budget.",
    remainingThisMonth: "remaining this month.",
    budgetExceeded: "Budget exceeded.",
    editBudget: "Edit Budget",
    budgetAnalysis: "Budget Analysis",
    budgetHealth: {
      healthy: "Healthy",
      warning: "Warning",
      full: "Full",
      unlimited: "Unlimited",
      critical: "Critical",
    },
    monthlyGroupBudget: "Monthly Group Budget",
    monthlyBudgetLimit: "Monthly Budget Limit",
    categoryBudget: "Category Budget",
    budgetAmount: "Budget Amount",
    groupBudget: "Group Budget",
    saveBudget: "Save Budget",
    invalidBudget: "Invalid Budget",
    budgetCannotBeNegative: "Budget cannot be negative.",
    categoryBudgetExceeded: "Category Budget Exceeded",
    categoryBudgetExceededMessage:
      "Total allocated budget is $${totalAllocated}. Group budget is only $${groupBudget}. Reduce another category budget or increase the group budget.",
    categoryBudgetSaved: "Category Budget Saved",
    invalidGroupBudget: "Invalid Group Budget",
    groupBudgetBelowAllocated:
      "Your category budgets already total $${allocated}. Increase the group budget or reduce category budgets first.",
    budgetUpdated: "Budget Updated",
    groupBudgetUpdatedMessage: "${groupName} budget updated to $${amount}.",
    backupRestored: "Backup Restored",
    backupRestoredMessage: "Your app data has been successfully restored.",
    invalidBackupFile: "Invalid Backup File",
    invalidBackupFileMessage: "The selected file is not a valid backup file.",
  },
});
